routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/cache', function () {

    \Illuminate\Support\Facades\Artisan::call('key:generate');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('route:clear');
    return 'Commands run successfully Cleared.';
});
//Frontend Routes

Route::get('/', 'FrontendController@index')->name('index');
Route::get('about-us', 'FrontendController@aboutUs')->name('about-us');
Route::get('products', 'FrontendController@products')->name('products');
Route::get('contact-us', 'FrontendController@contactUs')->name('contact-us');
Route::get('csr', 'FrontendController@csr')->name('csr');
Route::get('product/detail/{name}', 'FrontendController@productDetail')->name('product.detail');
Route::get('go-green', 'FrontendController@goGreen')->name('go.green');
Route::get('research-&-development', 'FrontendController@researchAndDevelopment')->name('research.and.development');
Route::get('events', 'FrontendController@events')->name('events');
Route::get('medical-care', 'FrontendController@medicalCare')->name('medical.care');
Route::resource('/contacts', 'GetInTouchController', [
    'only' => ['create', 'store']
]);
Route::resource('/getquote', 'GetAQuoteController', [
    'only' => ['create', 'store']
]);


//Backend Routes
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('forget-password', 'AccountController@getEmail');
Route::post('forget-password', 'AccountController@postEmail');
Route::get('reset-password/{token}', 'AccountController@getPassword');
Route::post('reset-password', 'AccountController@updatePassword');
Route::middleware(['auth'])->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('settings', 'Backend\SettingController', [
            'only' => ['index', 'update']
        ]);
        Route::resource('contacts', 'GetInTouchController', [
            'only' => ['index', 'destroy']
        ]);
        Route::resource('getquote', 'GetAQuoteController', [
            'only' => ['index']
        ]);
        Route::resource('csr', 'Backend\CSRController');
        Route::resource('events', 'Backend\EventController');
        Route::resource('products', 'Backend\ProductController');
        Route::resource('product-variants', 'Backend\ProductVariantController');
    });
});


//Ajax Routes
Route::prefix('ajax')->name('ajax.')->group(function () {
    Route::get('product/category', 'Backend\AjaxController@productCategory')->name('product.category');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = "products";
    protected $guarded = [];

    public function getImagePathAttribute()
    {
        return asset('uploads/products/' . $this->image);
    }

    public function productVariants()
    {
        return $this->hasMany(ProductVariant::class, 'product_id', 'id');

    }

}

app/Http/Controllers/Backend/AjaxController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class AjaxController extends Controller
{
    public function productCategory(Request $request)
    {
        $response = array('status' => '', 'message' => "", 'data' => array());

        $validator = Validator::make($request->all(), [
            'type' => 'required'
        ], [
            'type.required' => "Type is Required.",
        ]);

        if (!$validator->fails()) {
            $products = Product::where('type', $request->type)->get();

            $response['status'] = 'success';
            $response['data'] = [
                'products' => $products,
            ];
        } else {
            $response['status'] = 'error';
            $response['message'] = "Validation Errors.";
            $response['data'] = $validator->errors()->toArray();
        }

        return $response;
    }


}

app/Http/Controllers/Backend/CSRController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;

use App\Models\CSR;
use Illuminate\Http\Request;

class CSRController extends Controller
{
    public function __construct()
    {

    }

    public function index()
    {

        $csrs = CSR::all();
        return view('backend.csr.index', compact('csrs'));
    }

    public function create()
    {
        return view('backend.csr.create');
    }

    public function store(Request $request)
    {

        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',
            'background_image' => 'required',
            'image' => 'required',
            'icon_one' => 'required',
            'icon_two' => 'required',
            'icon_three' => 'required',
            'icon_four' => 'required',

        ], [
            'title.required' => 'Title is required.',
            'description.required' => 'Description is required.',
            'background_image.required' => 'Background Image is required.',
            'image.required' => 'Image is required.',
            'icon_one.required' => 'Icon One is required.',
            'icon_two.required' => 'Icon Two is required.',
            'icon_three.required' => 'Icon Three is required.',
            'icon_four.required' => 'Icon Four is required.',
        ]);

        $var = date_create();
        $time = date_format($var, 'YmdHis');
        if ($request->has('background_image')) {
            $image = $request->file('background_image');
            $name = $time . '-' . $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/csr');
            $image->move($destinationPath, $name);
            $background_image = $name;
        } else {
            $background_image = 'default.png';
        }

        if ($request->has('image')) {
            $image = $request->file('image');
            $name = $time . '-' . $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/csr');
            $image->move($destinationPath, $name);
            $profile_image = $name;
        } else {
            $profile_image = 'default.png';
        }

        if ($request->has('icon_one')) {
            $image = $request->file('icon_one');
            $name = $time . '-' . $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/csr');
            $image->move($destinationPath, $name);
            $icon_one = $name;
        } else {
            $icon_one = 'default.png';
        }

        if ($request->has('icon_two')) {
            $image = $request->file('icon_two');
            $name = $time . '-' . $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/csr');
            $image->move($destinationPath, $name);
            $icon_two = $name;
        } else {
            $icon_two = 'default.png';
        }

        if ($request->has('icon_three')) {
            $image = $request->file('icon_three');
            $name = $time . '-' . $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/csr');
            $image->move($destinationPath, $name);
            $icon_three = $name;
        } else {
            $icon_three = 'default.png';
        }
        if ($request->has('icon_four')) {
            $image = $request->file('icon_four');
            $name = $time . '-' . $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/csr');
            $image->move($destinationPath, $name);
            $icon_four = $name;
        } else {
            $icon_four = 'default.png';
        }

        $csr = CSR::create([
            'title' => $request->title,
            'description' => $request->description,
            'image' => $profile_image,
            'background_image' => $background_image,
            'icon_one' => $icon_one,
            'icon_two' => $icon_two,
            'icon_three' => $icon_three,
            'icon_four' => $icon_four,
        ]);

        return redirect()->route('admin.csr.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'CSR created successfully.'
            ]);
    }

    public function edit($id)
    {
        $csr = CSR::find($id);
        return view('backend.csr.edit', compact('csr'));


    }

    public function update(Request $request, $id)
    {

        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',

        ], [
            'title.required' => 'Title is required.',
            'description.required' => 'Description is required.',
        ]);

        $csr = CSR::find($id);


        $var = date_create();
        $time = date_format($var, 'YmdHis');
        if ($request->has('background_image')) {
            $image = $request->file('background_image');
            $name = $time . '-' . $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/csr');
            $image->move($destinationPath, $name);
            $background_image = $name;
        } else {
            $background_image =  $csr->background_image;;
        }

        if ($request->has('image')) {
            $image = $request->file('image');
            $name = $time . '-' . $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/csr');
            $image->move($destinationPath, $name);
            $profile_image = $name;
        } else {
            $profile_image = $csr->image;
        }

        if ($request->has('icon_one')) {
            $image = $request->file('icon_one');
            $name = $time . '-' . $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/csr');
            $image->move($destinationPath, $name);
            $icon_one = $name;
        } else {
            $icon_one = $csr->icon_one;
        }

        if ($request->has('icon_two')) {
            $image = $request->file('icon_two');
            $name = $time . '-' . $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/csr');
            $image->move($destinationPath, $name);
            $icon_two = $name;
        } else {
            $icon_two = $csr->icon_two;
        }

        if ($request->has('icon_three')) {
            $image = $request->file('icon_three');
            $name = $time . '-' . $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/csr');
            $image->move($destinationPath, $name);
            $icon_three = $name;
        } else {
            $icon_three = $csr->icon_three;
        }
        if ($request->has('icon_four')) {
            $image = $request->file('icon_four');
            $name = $time . '-' . $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/csr');
            $image->move($destinationPath, $name);
            $icon_four = $name;
        } else {
            $icon_four = $csr->icon_four;
        }


        $csr->update([
            'title' => $request->title,
            'description' => $request->description,
            'background_image' => $background_image,
            'image' => $profile_image,
            'icon_one' => $icon_one,
            'icon_two' => $icon_two,
            'icon_three' => $icon_three,
            'icon_four' => $icon_four,
        ]);

        return redirect()->route('admin.csr.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'CSR updated successfully.'
            ]);
    }

    public function destroy($id)
    {
        $csr = CSR::findOrFail($id);
        $csr->delete();

        return redirect()->route('admin.csr.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'CSR has been deleted Successfully.'
            ]);
    }
}

app/Http/Controllers/Backend/EventController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Event;
use Illuminate\Http\Request;

class EventController extends Controller
{
    public function __construct()
    {

    }

    public function index()
    {

        $events = Event::all();
        return view('backend.events.index', compact('events'));
    }

    public function create()
    {
        return view('backend.events.create');
    }

    public function store(Request $request)
    {

        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',
            'image' => 'required',

        ], [
            'title.required' => 'Title is required.',
            'description.required' => 'Description is required.',
            'image.required' => 'Image is required.',
        ]);

        $var = date_create();
        $time = date_format($var, 'YmdHis');

        if ($request->has('image')) {
            $image = $request->file('image');
            $name = $time . '-' . $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/events');
            $image->move($destinationPath, $name);
            $profile_image = $name;
        } else {
            $profile_image = 'default.png';
        }


        $event = Event::create([
            'title' => $request->title,
            'description' => $request->description,
            'image' => $profile_image,

        ]);

        return redirect()->route('admin.events.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Event created successfully.'
            ]);
    }

    public function edit($id)
    {
        $event = Event::find($id);
        return view('backend.events.edit', compact('event'));


    }

    public function update(Request $request, $id)
    {

        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',

        ], [
            'title.required' => 'Title is required.',
            'description.required' => 'Description is required.',
        ]);

        $event = Event::find($id);


        $var = date_create();
        $time = date_format($var, 'YmdHis');


        if ($request->has('image')) {
            $image = $request->file('image');
            $name = $time . '-' . $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/events');
            $image->move($destinationPath, $name);
            $profile_image = $name;
        } else {
            $profile_image = $event->image;
        }


        $event->update([
            'title' => $request->title,
            'description' => $request->description,
            'image' => $profile_image,
        ]);

        return redirect()->route('admin.events.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Event updated successfully.'
            ]);
    }

    public function destroy($id)
    {
        $event = Event::findOrFail($id);
        $event->delete();

        return redirect()->route('admin.events.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Event has been deleted Successfully.'
            ]);
    }
}

app/Http/Controllers/Backend/SettingController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Setting;
use Illuminate\Http\Request;

class SettingController extends Controller
{
    public function __construct()
    {

    }

    public function index()
    {
        $setting = Setting::first();
        return view('backend.settings.index', compact('setting'));
    }


    public function update(Request $request, $id)
    {
        $setting = Setting::find($id);
        if ($request->has('image')) {
            $image = $request->file('image');
            $name = $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/logo');
            $imagePath = $destinationPath . "/" . $name;
            $image->move($destinationPath, $name);
            $logo = $name;
        } else {

            $logo = $setting->logo;
        }
        if ($request->has('footer_logo')) {
            $image = $request->file('footer_logo');
            $name = $image->getClientOriginalName();
            $destinationPath = public_path('/uploads/banner');
            $imagePath = $destinationPath . "/" . $name;
            $image->move($destinationPath, $name);
            $footer_logo = $name;
        } else {
            $footer_logo = $setting->footer_logo;
        }

        $setting->update([
            'status' => $request->status,
            'logo' => $logo,
            'banner' => $footer_logo
        ]);
        return redirect()->route('admin.settings.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Setting updated successfully.'
            ]);

    }
}

resources/views/backend/products/edit.blade.php
@extends('layouts.master')
@section('title','Products')
@push('css')
    <style>
    </style>
@endpush
@section('content')


    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Edit {{ __('Product') }}
                        </h3>
                    </div>
                </div>

            </div>


            <div class="m-portlet__body">
                <div class="col-lg-12">
                    <div class="m-portlet">
                        <form class="m-form" method="post" action="{{ route('admin.products.update',$product->id) }}"
                              id="create"
                              enctype="multipart/form-data" role="form">
                            @method('patch')
                            @csrf
                            <div class="m-portlet__body">
                                <div class="m-form__section m-form__section--first">


                                    <div class="form-group row">
                                        <div class="col-md-6">
                                            <label for="title"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('Title') }}
                                                <span class="mandatorySign">*</span></label>
                                            <input id="title" type="text"
                                                   class="form-control @error('title') is-invalid @enderror"
                                                   name="title" value="{{ old('title',$product->title) }}"
                                                   autocomplete="title" autofocus>

                                            @error('title')
                                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                            @enderror
                                        </div>
                                        <div class="col-md-6">
                                            <label for="type"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('Type') }} <span
                                                    class="mandatorySign">*</span></label>

                                            <select id="type"
                                                    class="form-control cities @error('type') is-invalid @enderror"
                                                    name="type" autocomplete="type">
                                                <option
                                                    value="" {{ (old('type',$product->type) == '') ? 'selected' : '' }}>
                                                    Select an
                                                    option
                                                </option>
                                                <option
                                                    value="apparels" {{ (old('type',$product->type) == 'apparels') ? 'selected' : '' }}>
                                                    Apparels
                                                </option>
                                                <option
                                                    value="balls" {{ (old('type',$product->type) == 'balls') ? 'selected' : '' }}>
                                                    Balls
                                                </option>
                                                <option
                                                    value="gloves" {{ (old('type',$product->type) == 'gloves') ? 'selected' : '' }}>
                                                    Gloves
                                                </option>
                                                <option
                                                    value="bags" {{ (old('type') == 'bags') ? 'selected' : '' }}>
                                                    Bags
                                                </option>
                                            </select>

                                            @error('type')
                                            <span class="invalid-feedback" role="alert">
                                              <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="form-group row">
                                        <div class="col-md-6">
                                            <label for="image"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('Image') }}</label>
                                            <input value="{{old('image')}}" type="file"
                                                   class="form-control @error('image') is-invalid @enderror"
                                                   onchange="readURL(this)" id="image"
                                                   name="image" style="padding: 9px; cursor: pointer">
                                            <img width="300" height="200" class="img-thumbnail"
                                                 id="img"
                                                 style="display:{{($product->image) ? 'block' : 'none'}};"
                                                 src="{{ $product->image_path }}"
                                                 alt="your image"/>

                                            @error('image')
                                            <span class="invalid-feedback" role="alert">
                                              <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>

                                    </div>
                                </div>
                            </div>

                            <div class="m-portlet__foot m-portlet__foot--fit text-md-right">
                                <div class="m-form__actions m-form__actions">
                                    <a href="{{ route('admin.products.index') }}" class="btn btn-info">Back</a>
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('SAVE') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                        <!--end::Form-->
                    </div>
                    <!--end::Portlet-->
                </div>
            </div>
        </div>
    </div>
@endsection


@push('js')


    <script type="text/javascript">
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#img').attr('src', e.target.result);
                    $('#img').css("display", "block");
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
@endpush

resources/views/backend/products/index.blade.php
@extends('layouts.master')
@section('title','Products')
@push('css')
    <style>
    </style>
@endpush
@section('content')

    <div class="m-content">
        <!--Begin::Section-->
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Products
                        </h3>
                    </div>
                </div>

                <div class="m-portlet__head-tools">
                    <ul class="m-portlet__nav">
                        <li class="m-portlet__nav-item">
                            <a href="{{ route('admin.products.create') }}"
                               class="btn btn-accent m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                                <span>
                                    <i class="la la-plus"></i>
                                    <span>Add Products</span>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="m-portlet__body">
                <input type="hidden">

                <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                    <thead>
                    <tr>

                        <th>Sr No.</th>
                        <th>Title</th>
                        <th>Type</th>
                        <th style="width: 10%;">Image</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if(!empty($products))
                        @foreach($products as $product)
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>{{ucfirst($product->title)}}</td>
                                <td>{{ucfirst($product->type)}}</td>
                                <td>
                                    <img width="300" height="200" class="img-thumbnail"
                                         style="display:{{($product->image) ? '' : 'none'}};
                                             object-fit: contain;"
                                         id="img"
                                         src="{{ $product->image_path}}"
                                         alt="your image"/>
                                </td>
                                <td nowrap style="width: 30%;">
                                    <a href="{{route('admin.products.edit',$product->id)}}"
                                       class="btn btn-sm btn-info pull-left ">Edit</a>
                                    <form method="post" action="{{ route('admin.products.destroy', $product->id) }}"
                                          id="delete_{{ $product->id }}">
                                        @csrf
                                        @method('DELETE')
                                        <a class="btn btn-sm btn-danger m-left"
                                           href="javascript:void(0)"
                                           onclick="if(confirmDelete()){ document.getElementById('delete_<?=$product->id?>').submit(); }">
                                            Delete
                                        </a>
                                    </form>
                                </td>
                            </tr>

                        @endforeach
                    @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@push('models')

@endpush
@push('js')
    <script>
        $("#m_table_1").dataTable({
            "columnDefs": [
                {orderable: false, targets: [3, 4]}
            ],
        });


    </script>
@endpush